var jwt = require('jsonwebtoken');
var azureOpenId = require('./azure-open-id')("https://login.microsoftonline.com/common/.well-known/openid-configuration");
var jwtOptions = { ignoreExpiration: true, algorithms: ['RS256'] };


var oldToken = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20vIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDU0MGZjMmUtZGIyNC00YWQ3LThjNTEtOTlmMDBiMTNmMTM0LyIsImlhdCI6MTQ0ODc2MTk0NSwibmJmIjoxNDQ4NzYxOTQ1LCJleHAiOjE0NDg3NjU4NDUsImFjciI6IjEiLCJhbXIiOlsicHdkIl0sImFwcGlkIjoiYWQzY2Y1Y2QtMDUxMi00MWE3LThiNWQtMmQ4ODhhOTUxYWIwIiwiYXBwaWRhY3IiOiIxIiwiZmFtaWx5X25hbWUiOiJCb3V2aWVyIiwiZ2l2ZW5fbmFtZSI6ImplcmVteSIsImlwYWRkciI6IjE2Mi4yNTAuNDYuMTMwIiwibmFtZSI6ImplcmVteSBCb3V2aWVyIiwib2lkIjoiNTVjNzZkMGYtYzk4NS00OTk0LWEyY2YtNDAyZjQ2YmExODI1IiwicHVpZCI6IjEwMDM3RkZFOEM5RUZBODgiLCJzY3AiOiJDYWxlbmRhcnMuUmVhZCBDYWxlbmRhcnMuUmVhZFdyaXRlIENvbnRhY3RzLlJlYWQgQ29udGFjdHMuUmVhZFdyaXRlIERpcmVjdG9yeS5BY2Nlc3NBc1VzZXIuQWxsIERpcmVjdG9yeS5SZWFkLkFsbCBEaXJlY3RvcnkuUmVhZFdyaXRlLkFsbCBGaWxlcy5SZWFkIEZpbGVzLlJlYWQuQWxsIEZpbGVzLlJlYWQuU2VsZWN0ZWQgRmlsZXMuUmVhZFdyaXRlIEZpbGVzLlJlYWRXcml0ZS5BbGwgRmlsZXMuUmVhZFdyaXRlLkFwcEZvbGRlciBGaWxlcy5SZWFkV3JpdGUuU2VsZWN0ZWQgR3JvdXAuUmVhZC5BbGwgR3JvdXAuUmVhZFdyaXRlLkFsbCBNYWlsLlJlYWQgTWFpbC5SZWFkV3JpdGUgTWFpbC5TZW5kIE5vdGVzLkNyZWF0ZSBOb3Rlcy5SZWFkIE5vdGVzLlJlYWQuQWxsIE5vdGVzLlJlYWRXcml0ZSBOb3Rlcy5SZWFkV3JpdGUuQWxsIE5vdGVzLlJlYWRXcml0ZS5DcmVhdGVkQnlBcHAgb2ZmbGluZV9hY2Nlc3Mgb3BlbmlkIFBlb3BsZS5SZWFkIFNpdGVzLlJlYWQuQWxsIFRhc2tzLlJlYWRXcml0ZSBVc2VyLlJlYWQgVXNlci5SZWFkLkFsbCBVc2VyLlJlYWRCYXNpYy5BbGwgVXNlci5SZWFkV3JpdGUgVXNlci5SZWFkV3JpdGUuQWxsIiwic3ViIjoiLXR0a0wyMFdZNHB3dnI4WWZoMG11M2hCaHI1UTJueklKdWFJbkdhTzBaayIsInRpZCI6ImQ1NDBmYzJlLWRiMjQtNGFkNy04YzUxLTk5ZjAwYjEzZjEzNCIsInVuaXF1ZV9uYW1lIjoiamVyZW15QGplcmVteUNvcnAub25taWNyb3NvZnQuY29tIiwidXBuIjoiamVyZW15QGplcmVteUNvcnAub25taWNyb3NvZnQuY29tIiwidmVyIjoiMS4wIn0.N80inw_9InUgtGncoqyTniiQQq03NPpF1FwLMxoU2rzmNDnBIopyvChfjqtzknVWBHuRQrDewdPt2i5_8YICNlmCnm749Zt3Ahz0B9tcXm_kEfmvVWBWG7V52G9vuJ2O7gXK7SvfhDGJW9fpOeQki-nqhsm66BS32Ih_s4saKzo6tV5V8-ctgqKchWo2LUxYSMppSTizy42P_3tWlBlVbfZeVOIoEIBJalwrUDU-gB_Y8kfKKVuzbnKesR1oJBV2p5rTdahiK8ZRJroD3bH6ZWbCP6Omq7rtKbQbaylTyKV9d-ud2ZI3MdnoUHinMwpdJOz1NVOqU9J3R7T1iBQFPQ";

var Token = "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ikk2b0J3NFZ6QkhPcWxlR3JWMkFKZEE1RW1YYyIsImtpZCI6Ikk2b0J3NFZ6QkhPcWxlR3JWMkFKZEE1RW1YYyJ9.eyJhdWQiOiIxMTRjZjU5OC00ZmZmLTQyYzMtODBlOS05Y2QxMDI1MjA2YWYiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9kNTQwZmMyZS1kYjI0LTRhZDctOGM1MS05OWYwMGIxM2YxMzQvIiwiaWF0IjoxNDc2MzE5NzkxLCJuYmYiOjE0NzYzMTk3OTEsImV4cCI6MTQ3NjMyMzY5MSwiYW1yIjpbInB3ZCJdLCJjX2hhc2giOiI1OGhzWXZkdktocmlmWWYyenU0SktRIiwiZmFtaWx5X25hbWUiOiJCb3V2aWVyIiwiZ2l2ZW5fbmFtZSI6ImplcmVteSIsImlwYWRkciI6IjE2Mi4yNTAuNDcuMTQ2IiwibmFtZSI6ImplcmVteSBCb3V2aWVyIiwibm9uY2UiOiI3MzYyQ0FFQS05Q0E1LTRCNDMtOUJBMy0zNEQ3QzMwM0VCQTciLCJvaWQiOiI1NWM3NmQwZi1jOTg1LTQ5OTQtYTJjZi00MDJmNDZiYTE4MjUiLCJzdWIiOiJRNWRiaVdMZnh2OGhPSS1pbFo0dVVKa2NwWnFodDJVQy1JY3VpbThkakNJIiwidGlkIjoiZDU0MGZjMmUtZGIyNC00YWQ3LThjNTEtOTlmMDBiMTNmMTM0IiwidW5pcXVlX25hbWUiOiJqZXJlbXlAamVyZW15Q29ycC5vbm1pY3Jvc29mdC5jb20iLCJ1cG4iOiJqZXJlbXlAamVyZW15Q29ycC5vbm1pY3Jvc29mdC5jb20iLCJ2ZXIiOiIxLjAifQ.FhBtbjvCE_Dvci8h1Emmzpt6Vyu802lbiDj6hPEIJ4LdlZP4ruZeYjdX7RPyjZzdKR6Op0t3IIegaivqoWFhIZrhX-YwVu9ACRf-kzcwi2sm7JBSuVldAbXhTf2UkCM3jAh9Ox67WMmVuIdISEvAfS6Jr39DPyh0e0Yq_ifHMInoj4Gkr0aAE77hNWQsdHSb0Dmvg-gzow7RrVRtiBiCriIYlXeyaPrFF5YXefterE76RDl3YeD5xc_qg4WIyqiMNdzzxudd07EzROFyOM0lnuwGApYpyC6iiOmw9VGcqaQ42CtCvXr1UmxHFxqtkkWTJklLIQkWWBDK3nTMnIHwdg";

//https://login.microsoftonline.com/common/.well-known/openid-configuration
//YbRAQRYcE_motWVJKHrwLBbd_9s
//MnC_VZcATfM5pOYiJHMba9goEKY
//I6oBw4VzBHOqleGrV2AJdA5EmXc


/*var pkPromise = azureOpenId.getAzureAdJwkById("I6oBw4VzBHOqleGrV2AJdA5EmXc");
pkPromise.then(function (jwk) {
    var pem = azureOpenId.getPemFromJwkForge(jwk);
    azureOpenId.printPem(pem,"pk.pem");
    jwt.verify(Token,pem, jwtOptions, function (err, decoded) {
        console.log(decoded)
    });
})
.catch(function (err) {
    console.log(err);
});
*/
var pkPromise = azureOpenId.getPemByJwkId("I6oBw4VzBHOqleGrV2AJdA5EmXc",true);
pkPromise.then(function (pem) {
    jwt.verify(Token,pem, jwtOptions, function (err, decoded) {
        console.log(decoded)
    });
})
.catch(function (err) {
    console.log(err);
});





